BankManage/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bmanage/', include('bmanage.urls'))
]

bmanage/urls.py
# 引入path
from django.urls import path
from django.conf.urls import url
from . import views
# 正在部署的应用的名称
app_name = 'bmanage'

urlpatterns = [
    url(r'^hello/', views.login, name='login'),
    url(r'^cusadd/', views.customer_manage_add, name='cusadd'),
    url(r'^cusdel/', views.customer_manage_del, name='cusdel'),
    url(r'^cusmod/', views.customer_manage_mod, name='cusmod'),
    url(r'^cusfod/', views.customer_manage_found, name='cusfod'),
    url(r'^accadd/', views.account_add, name='accadd'),
    url(r'^accdel/', views.account_del, name='accdel'),
    url(r'^accmod/', views.account_mod, name='accmod'),
    url(r'^accfod/', views.account_found, name='accfod'),
    url(r'^loanadd/', views.loan_add, name='loanadd'),
    url(r'^loandel/', views.loan_del, name='loandel'),
    url(r'^loanfound/', views.loan_found, name='loanfound'),
    url(r'^loanissue$', views.loan_issue, name='loanissue'),
    url(r'^savestatistic$', views.save_statistics, name='savestatistic'),
    url(r'^loanstatistic$', views.loan_statistics, name='loanstatistic')
    # 目前还没有urls
]

templates/accountAdd.html
<!-- 定义导航栏 -->
{% extends 'base.html' %}
{% block details %}

<div class="container">
  <h2>账户开户</h2>
  <form action="" method="post">
      {% csrf_token %}
      <div class="form-group">
      <label for="accountID">Account ID:</label>
          <em style="color: red;">*</em>
      <input type="text" class="form-control" id="accID" name="accID" maxlength="6" minlength="6" required="required" placeholder="Enter 6-digit Account ID">
    </div>
    <div class="form-group">
        <label for="cusID">Customer ID:</label>
        <em style="color: red;">*</em>
    </div>
      <select multiple class="form-control" id="cusID" name="cusIDList" required="required">
          {% for obj in obj_list %}
            <option value="{{ obj.cusid }}">{{ obj.cusid }}</option>
          {% endfor %}
      </select>
{#      <div class="form-group">#}
{#      <label for="ID">ID:</label>#}
{#          <em style="color: red;">*</em>#}
{#      <input type="text" class="form-control" id="cusID" name="cusID" required="required" placeholder="Enter ID">#}
{#    </div>#}
      <div class="form-group">
      <label for="bank">Bank Name:</label>
    </div>
      <select class="form-control" id="bank" name="bank" required="required">
          {% for bank in bank_list %}
            <option value="{{ bank.bankname }}">{{ bank.bankname }}</option>
          {% endfor %}
      </select>
      <div class="form-group">
      <label for="settime">Datetime:</label>
      <input type="datetime-local" class="form-control" id="settime" name="settime"  placeholder="Enter Datetime">
    </div>
      <div class="form-group">
      <label for="money">Money:</label>
          <em style="color: red;">*</em>
      <input type="number" step="0.01" class="form-control" id="Money" name="money" required="required" placeholder="Enter Money">
    </div>
      <select name="accType" id="accountType" onchange="show_or_hide(this.value)">
        <option value="SavingAccount">Save Account</option>
        <option value="CheckingAccount">Check Account</option>
    </select>
      <div class="saveAcc">
          <div class="form-group" type="hidden">
              <label for="interestrate">Interestrate:</label>
              <input type="number" step="0.01" class="form-control" id="interestrate" name="interestrate" placeholder="Enter Interestrate">
          </div>
          <div class="form-group" type="hidden">
              <label for="savetype">Savetype:</label>
              <input type="text" class="form-control" id="savetype" name="savetype" placeholder="Enter savetype">
          </div>
      </div>
      <div class="checkAcc">
          <div class="form-group" type="hidden">
              <label for="overdraft">Overdraft:</label>
              <input type="number" class="form-control" id="overdraft" name="overdraft" placeholder="Enter Overdraft">
          </div>
      </div>
    <button type="submit" class="btn btn-primary">Submit</button>
      <script>
          $(".checkAcc").hide();
          function show_or_hide(v){
	    	if(v == "SavingAccount"){
	    		$(".saveAcc").show();
	    		$(".checkAcc").hide();
	    	}else if(v =="CheckingAccount"){
	    		$(".saveAcc").hide();
	    		$(".checkAcc").show();
	    	}
	    }
      </script>
  </form>
    {% if messages %}
        <script>
            {% for msg in messages %}
                alert('{{ msg.message | escapejs  }}');
            {% endfor %}
        </script>
    {% endif %}
</div>

{% endblock %}

templates/accountFound.html
<!-- 定义导航栏 -->
{% extends 'base.html' %}
{% block details %}

<div class="container">
  <h2>账户信息查询</h2>
  <form action="/bmanage/accfod/" method="post">
      {% csrf_token %}
      <div class="form-group">
      <label for="accID">Account ID:</label>
          <em style="color: red;">*</em>
          <select class="form-control" id="sel1" name="accID">
              {% for accID in accID_list %}
                  <option value="{{ accID.accountid }}">{{ accID.accountid }}</option>
              {% endfor %}
          </select>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
    <table class="table table-striped">
        <thead>
        <th>Account ID</th>
        <th>Bank</th>
        <th>Type</th>
        <th>Money</th>
        <th>Setting Time</th>
        </thead>
        <tbody id="search-content">
        {% for account_info in account_list %}
            <tr>
                <td>{{ account_info.0 }}</td>
                <td>{{ account_info.1 }}</td>
                <td>{{ account_info.2 }}</td>
                <td>{{ account_info.3 }}</td>
                <td>{{ account_info.4 }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="card-footer text-white text-center">
      <div>
        <a class="btn btn-primary" href="#search-form" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="search-form"><i class="fa fas fa-search"></i> 搜索</a>
      </div>
      <div class="collapse" id="search-form">
      <div class="form-group pt-3 mb-0">
        <input id="search-input" type="text" class="form-control" placeholder="输入以开始搜索">
      </div>
      </div>
    </div>
    {% if messages %}
        <script>
            {% for msg in messages %}
                alert('{{ msg.message }}');
            {% endfor %}
        </script>
    {% endif %}
</div>

{% endblock %}

templates/accountMod.html
<!-- 定义导航栏 -->
{% extends 'base.html' %}
{% block details %}

<div class="container">
  <h2>账户信息修改</h2>
  <form action="/bmanage/accfod/" method="post">
      {% csrf_token %}
      <div class="form-group">
      <label for="accID">Account ID:</label>
          <em style="color: red;">*</em>
          <select class="form-control" id="sel1" name="accID">
              {% for accID in accID_list %}
                  <option value="{{ accID.accountid }}">{{ accID.accountid }}</option>
              {% endfor %}
          </select>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
    {% if messages %}
        <script>
            {% for msg in messages %}
                alert('{{ msg.message }}');
            {% endfor %}
        </script>
    {% endif %}
</div>

{% endblock %}

templates/accountMod2.html
{% extends 'base.html' %}
{% block details %}

    <div class="container">
  <h2>账户信息修改</h2>
  <form action="/bmanage/accmod/" method="post">
      {% csrf_token %}
      <div class="form-group">
      <label for="accountID">Account ID:</label>
          <em style="color: red;">*</em>
      <input type="text" class="form-control" id="accID" name="accID" required="required" placeholder="Enter Account ID" value="{{ acc_id }}" readonly>
    </div>
      <div class="form-group">
      <label for="ID">ID:</label>
          <em style="color: red;">*</em>
          {% for cus_obj in cus_obj_list %}
            <input type="text" class="form-control" id="cusID" name="cusID" required="required" value="{{ cus_obj.cusid.cusid }}" readonly>
          {% endfor %}
    </div>
      <div class="form-group">
      <label for="bank">Bank Name:</label>
      <input type="text" class="form-control" id="bank" name="bank" placeholder="Enter Bank Name" value="{{ bank.bankname }}" readonly>
    </div>
      <div class="form-group">
      <label for="settime">Datetime:</label>
      <input type="text" class="form-control" id="settime" name="settime" placeholder="Enter Datetime" value="{{ acc_obj.settime }}" readonly>
    </div>
      <div class="form-group">
      <label for="money">Money:</label>
          <em style="color: red;">*</em>
      <input type="number" step="0.01" class="form-control" id="Money" name="money" required="required" placeholder="Enter Money" value="{{ acc_obj.money }}">
    </div>
         <div class="form-group">
             <input class="acctype" name="accType" value="{{ acc_type }}" readonly>
         </div>
      <div class="saveAcc">
          <div class="form-group" type="hidden">
              <label for="interestrate">Interestrate:</label>
              <input type="number" step="0.01" class="form-control" id="interestrate" name="interestrate" placeholder="Enter Interestrate" value="{{ save_obj.interestrate }}">
          </div>
          <div class="form-group" type="hidden">
              <label for="savetype">Savetype:</label>
              <input type="text" class="form-control" id="savetype" name="savetype" placeholder="Enter savetype" value="{{ save_obj.savetype }}">
          </div>
      </div>
      <div class="checkAcc">
          <div class="form-group" type="hidden">
              <label for="overdraft">Overdraft:</label>
              <input type="number" class="form-control" id="overdraft" name="overdraft" placeholder="Enter Overdraft" value="{{ check_obj.overdraft }}">
          </div>
      </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
    {% if acc_type == "SavingAccount" %}
        <script>
            $(".saveAcc").show();
            $(".checkAcc").hide();
        </script>
    {% elif acc_type == "CheckingAccount" %}
        <script>
            $(".saveAcc").hide();
            $(".checkAcc").show();
        </script>
    {% endif %}
    {% if messages %}
        <script>
            {% for msg in messages %}
                alert('{{ msg.message }}');
            {% endfor %}
        </script>
    {% endif %}
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>银行信息管理系统</title>
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/popper.js/1.15.0/umd/popper.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="../static/echarts.min.js"></script>
</head>

<body>

<div class="jumbotron text-center" style="margin-bottom:0">
  <h1>银行信息管理系统</h1>
</div>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark" role="navigation">
  <a class="navbar-brand" href="#">信息管理</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="nav navbar-nav">
      <li class="dropdown open">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">客户管理<b class="caret"></b></a>
        <ul class="dropdown-menu" role="menu" >
            <li><a class="dropdown-item" href="{% url "bmanage:cusadd" %}" style="color: black;">客户信息添加</a></li>
            <li class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url "bmanage:cusdel" %}" style="color: black;">客户信息删除</a></li>
            <li class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url "bmanage:cusmod" %}" style="color: black;">客户信息修改</a></li>
            <li class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url "bmanage:cusfod" %}" style="color: black;">客户信息查询</a></li>
        </ul>
      </li>
      <li class="dropdown open">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">账户管理<b class="caret"></b></a>
        <ul class="dropdown-menu" role="menu" >
            <li><a class="dropdown-item" href="{% url "bmanage:accadd" %}" style="color: black;">账户开户</a></li>
            <li class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url "bmanage:accdel" %}" style="color: black;">账户销户</a></li>
            <li class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url "bmanage:accmod" %}" style="color: black;">账户修改</a></li>
            <li class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url "bmanage:accfod" %}" style="color: black;">账户查询</a></li>
{#            <li class="dropdown-divider"></li>#}
{#            <li><a class="dropdown-item" href="#" style="color: black;">支票账户开户</a></li>#}
{#            <li class="dropdown-divider"></li>#}
{#            <li><a class="dropdown-item" href="#" style="color: black;">支票账户销户</a></li>#}
{#            <li class="dropdown-divider"></li>#}
{#            <li><a class="dropdown-item" href="#" style="color: black;">支票账户修改</a></li>#}
{#            <li class="dropdown-divider"></li>#}
{#            <li><a class="dropdown-item" href="#" style="color: black;">支票账户查询</a></li>#}
        </ul>
      </li>
      <li class="dropdown open">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">贷款管理<b class="caret"></b></a>
        <ul class="dropdown-menu" role="menu" >
            <li><a class="dropdown-item" href="{% url "bmanage:loanadd" %}" style="color: black;">贷款信息添加</a></li>
            <li class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url "bmanage:loandel" %}" style="color: black;">贷款信息删除</a></li>
            <li class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url "bmanage:loanfound" %}" style="color: black;">贷款信息查询</a></li>
            <li class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url "bmanage:loanissue" %}" style="color: black;">贷款发放</a></li>
        </ul>
      </li>
      <li class="dropdown open">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">业务统计<b class="caret"></b></a>
        <ul class="dropdown-menu" role="menu" >
            <li><a class="dropdown-item" href="{% url "bmanage:savestatistic" %}" style="color: black;">储蓄业务</a></li>
            <li class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url "bmanage:loanstatistic" %}" style="color: black;">贷款业务</a></li>
        </ul>
      </li>
    </ul>
  </div>
</nav>

<div class="container-fluid">
    <div class="row-fluid">

        <div class="col-md-9">

            <div id="doc">

                {% block details %}
                {% endblock %}

            </div>
        </div>
    </div>
</div>
<footer class="footer shadow py-3 py-md-4 border-top">
      <div class="container px-sm-0">
        <p class="text-muted my-0">
        <a href="https://github.com/JarvisUSTC/BankManage">Bank System</a>, Copyright &copy; 2020-2020 <a href="https://github.com/JarvisUSTC">JarvisUSTC</a>
        </p>
      </div>
</footer>
<script>
        document.getElementById('search-input').oninput = function() {
          var searchTerm = document.getElementById('search-input').value;
          var searchRegex = undefined;
          try {
            searchRegex = new RegExp(searchTerm);
          } catch {
            // Bad regex, ignore
          }
          var tbody = document.getElementById('search-content');

          for (let i = 0; i < tbody.children.length; i++) {
            var tr = tbody.children[i];
            var match = false;
            var texts = [];

            // Filter: Exclude last element because it contains only action buttons
            for (let j = 0; j < tr.children.length - 1; j++) {
              var td = tr.children[j];
              texts.push(td.innerText);
            }
            var text = texts.join("\n");

            if (text.indexOf(searchTerm) !== -1) {
              match = true;
            } else if (typeof searchRegex !== "undefined" && searchRegex.test(text)) {
              match = true;
            }
            tr.style.display = match ? "" : "none";
          }
        };
</script>
</body>
</html>

templates/customerAdd.html
<!-- 定义导航栏 -->
{% extends 'base.html' %}
{% block details %}

<div class="container">
  <h2>客户信息添加</h2>
  <form action="" method="post">
      {% csrf_token %}
      <div class="form-group">
      <label for="ID">ID:</label>
          <em style="color: red;">*</em>
      <input type="text" class="form-control" id="cusID" name="cusID" maxlength="18" minlength="18" required="required" placeholder="Enter your 18 - digit ID">
    </div>
      <div class="form-group">
      <label for="name">Name:</label>
          <em style="color: red;">*</em>
      <input type="text" class="form-control" id="cusName" name="cusName" required="required" placeholder="Enter Name">
    </div>
      <div class="form-group">
      <label for="phone">Phone Number:</label>
          <em style="color: red;">*</em>
      <input type="text" class="form-control" id="cusPhone" name="cusPhone" required="required" placeholder="Enter Phone Number">
    </div>
      <div class="form-group">
      <label for="address">Address:</label>
      <input type="text" class="form-control" id="cusAddress" name="address" placeholder="Enter Address">
    </div>
      <div class="form-group">
      <label for="contact_name">Contact Name:</label>
          <em style="color: red;">*</em>
      <input type="text" class="form-control" id="ContactName" name="contactName" required="required" placeholder="Enter Contact Name">
    </div>
      <div class="form-group">
      <label for="contact_phone">Phone Number:</label>
          <em style="color: red;">*</em>
      <input type="text" class="form-control" id="ContactPhone" name="contactPhone" required="required" placeholder="Enter Contact Phone Number">
    </div>
    <div class="form-group">
      <label for="contact_email">Email:</label>
      <input type="email" class="form-control" id="ContactEmail" name="contactEmail" placeholder="Enter Contact Email">
    </div>
      <div class="form-group">
      <label for="relation">Contact Relationship:</label>
          <em style="color: red;">*</em>
      <input type="text" class="form-control" id="relation" name="relation" required="required" placeholder="Enter Relationship">
    </div>
    <div class="form-group">
      <label for="loan_res">Loan responder:</label>
        <em style="color: red;">*</em>
      <select class="form-control" id="loan_res" name="loanRes" required="required">
          {% for res in res_list %}
            <option value="{{ res.empid }}">{{ res.empid }}</option>
          {% endfor %}
      </select>
    </div>
      <div class="form-group">
      <label for="acc_res">Account responder:</label>
      <em style="color: red;">*</em>
      <select class="form-control" id="acc_res" name="accRes" required="required">
          {% for res in res_list %}
            <option value="{{ res.empid }}">{{ res.empid }}</option>
          {% endfor %}
      </select>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
    {% if messages %}
        <script>
            {% for msg in messages %}
                alert('{{ msg.message }}');
            {% endfor %}
        </script>
    {% endif %}
</div>

{% endblock %}

templates/customerDel.html
<!-- 定义导航栏 -->
{% extends 'base.html' %}
{% block details %}

<div class="container">
  <h2>客户信息删除</h2>
  <form action="" method="post">
      {% csrf_token %}
      <div class="form-group">
      <label for="ID">ID:</label>
          <em style="color: red;">*</em>
          <select class="form-control" id="cusID" name="cusID" required="required">
          {% for obj in cus_list %}
            <option value="{{ obj.cusid }}">{{ obj.cusid }}</option>
          {% endfor %}
          </select>
      </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
    {% if messages %}
        <script>
            {% for msg in messages %}
                alert('{{ msg.message }}');
            {% endfor %}
        </script>
    {% endif %}
</div>

{% endblock %}

templates/customerMod.html
<!-- 定义导航栏 -->
{% extends 'base.html' %}
{% block details %}

<div class="container">
  <h2>客户信息修改</h2>
  <form action="/bmanage/cusfod/" method="post">
      {% csrf_token %}
      <div class="form-group">
          <label for="ID">ID:</label>
          <em style="color: red;">*</em>
          <select class="form-control" id="cusID" name="cusID" required="required">
          {% for obj in cus_list %}
            <option value="{{ obj.cusid }}">{{ obj.cusid }}</option>
          {% endfor %}
          </select>
      </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
    {% if messages %}
        <script>
            {% for msg in messages %}
                alert('{{ msg.message }}');
            {% endfor %}
        </script>
    {% endif %}
</div>

{% endblock %}

templates/customerMod2.html
{% extends 'base.html' %}
{% block details %}

    <div class="container">
        <div class="row" >
                      <form action="/bmanage/cusmod/" method="post">
                          {% csrf_token %}
                          <div class="form-group">
                              <label for="ID">ID:</label>
                                  <em style="color: red;">*</em>
                              <input type="text" class="form-control" id="cusID" name="cusID" required="required" value="{{ cus_obj.cusid }}" readonly>
                            </div>
                          <div class="form-group">
                          <label for="name">Name:</label>
                              <em style="color: red;">*</em>
                          <input type="text" class="form-control" id="cusName" name="cusName" required="required" placeholder="Enter Name" value="{{ cus_obj.cusname }}">
                        </div>
                          <div class="form-group">
                          <label for="phone">Phone Number:</label>
                              <em style="color: red;">*</em>
                          <input type="text" class="form-control" id="cusPhone" name="cusPhone" required="required" placeholder="Enter Phone Number" value="{{ cus_obj.cusphone }}">
                        </div>
                          <div class="form-group">
                          <label for="address">Address:</label>
                          <input type="text" class="form-control" id="cusAddress" name="address" placeholder="Enter Address" value="{{ cus_obj.address }}">
                        </div>
                          <div class="form-group">
                          <label for="contact_name">Contact Name:</label>
                              <em style="color: red;">*</em>
                          <input type="text" class="form-control" id="ContactName" name="contactName" required="required" placeholder="Enter Contact Name" value="{{ cus_obj.contact_name }}">
                        </div>
                          <div class="form-group">
                          <label for="contact_phone">Phone Number:</label>
                              <em style="color: red;">*</em>
                          <input type="text" class="form-control" id="ContactPhone" name="contactPhone" required="required" placeholder="Enter Contact Phone Number" value="{{ cus_obj.contact_phone }}">
                        </div>
                        <div class="form-group">
                          <label for="contact_email">Email:</label>
                          <input type="email" class="form-control" id="ContactEmail" name="contactEmail" placeholder="Enter Contact Email" value="{{ cus_obj.contact_email }}">
                        </div>
                          <div class="form-group">
                          <label for="relation">Contact Relationship:</label>
                              <em style="color: red;">*</em>
                          <input type="text" class="form-control" id="relation" name="relation" required="required" placeholder="Enter Relationship" value="{{ cus_obj.relation }}">
                        </div>
                          <div class="form-group">
                          <label for="loan_res">Loan responder:</label>
                              <em style="color: red;">*</em>
                              <select class="form-control" id="loan_res" name="loanRes" required="required">
                                  {% for res in res_list %}
                                    <option value="{{ res.empid }}">{{ res.empid }}</option>
                                  {% endfor %}
                              </select>
                          </div>
                          <div class="form-group">
                              <label for="acc_res">Account responder:</label>
                              <em style="color: red;">*</em>
                              <select class="form-control" id="acc_res" name="accRes" required="required">
                                  {% for res in res_list %}
                                    <option value="{{ res.empid }}">{{ res.empid }}</option>
                                  {% endfor %}
                              </select>
                          </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                      </form>
            {% if messages %}
                <script>
                    {% for msg in messages %}
                        alert('{{ msg.message }}');
                    {% endfor %}
                </script>
            {% endif %}
            </div>
    </div>
{% endblock %}

templates/customerfound.html
<!-- 定义导航栏 -->
{% extends 'base.html' %}
{% block details %}

<div class="container">
  <h2>客户信息查询</h2>
  <form action="/bmanage/cusfod/" method="post">
      {% csrf_token %}
      <div class="form-group">
      <label for="ID">ID:</label>
          <em style="color: red;">*</em>
          <select class="form-control" id="cusID" name="cusID" required="required">
          {% for obj in cus_list %}
            <option value="{{ obj.cusid }}">{{ obj.cusid }}</option>
          {% endfor %}
          </select>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
    <table class="table table-striped">
        <thead>
        <th>ID</th>
        <th>Name</th>
        <th>Account Responder</th>
        <th>Loan Responder</th>
        <th>Contact Name</th>
        </thead>
        <tbody id="search-content">
        {% for customer_info in customer_list %}
            <tr>
                <td>{{ customer_info.0 }}</td>
                <td>{{ customer_info.1 }}</td>
                <td>{{ customer_info.2 }}</td>
                <td>{{ customer_info.3 }}</td>
                <td>{{ customer_info.4 }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="card-footer text-white text-center">
      <div>
        <a class="btn btn-primary" href="#search-form" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="search-form"><i class="fa fas fa-search"></i> 搜索</a>
      </div>
      <div class="collapse" id="search-form">
      <div class="form-group pt-3 mb-0">
        <input id="search-input" type="text" class="form-control" placeholder="输入以开始搜索">
      </div>
      </div>
    </div>
    {% if messages %}
        <script>
            {% for msg in messages %}
                alert('{{ msg.message }}');
            {% endfor %}
        </script>
    {% endif %}
</div>

{% endblock %}

templates/loanAdd.html
<!-- 定义导航栏 -->
{% extends 'base.html' %}
{% block details %}

<div class="container">
  <h2>贷款信息添加</h2>
  <form action="" method="post">
      {% csrf_token %}
      <div class="form-group">
      <label for="loanID">Loan ID:</label>
          <em style="color: red;">*</em>
      <input type="text" class="form-control" id="loanID" name="loanID" maxlength="4" minlength="4" required="required" placeholder="Enter 4-digit Loan ID">
    </div>
    <div class="form-group">
        <label for="cusID">Customer ID:</label>
        <em style="color: red;">*</em>
    </div>
      <select multiple class="form-control" id="cusID" name="cusIDList" required="required">
          {% for obj in obj_list %}
            <option value="{{ obj.cusid }}">{{ obj.cusid }}</option>
          {% endfor %}
      </select>
{#      <div class="form-group">#}
{#      <label for="ID">ID:</label>#}
{#          <em style="color: red;">*</em>#}
{#      <input type="text" class="form-control" id="cusID" name="cusID" required="required" placeholder="Enter ID">#}
{#    </div>#}
      <div class="form-group">
      <label for="bank">Bank Name:</label>
    </div>
      <select class="form-control" id="bank" name="bank" required="required">
          {% for bank in bank_list %}
            <option value="{{ bank.bankname }}">{{ bank.bankname }}</option>
          {% endfor %}
      </select>
      <div class="form-group">
      <label for="money">Money:</label>
          <em style="color: red;">*</em>
      <input type="number" step="0.01" class="form-control" id="Money" name="money" required="required" placeholder="Enter Money">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
    {% if messages %}
        <script>
            {% for msg in messages %}
                alert('{{ msg.message }}');
            {% endfor %}
        </script>
    {% endif %}
</div>

{% endblock %}

templates/loanDel.html
<!-- 定义导航栏 -->
{% extends 'base.html' %}
{% block details %}

<div class="container">
  <h2>贷款信息删除</h2>
  <form action="" method="post">
      {% csrf_token %}
      <div class="form-group">
      <label for="loanID">Loan ID:</label>
          <em style="color: red;">*</em>
          <select class="form-control" id="sel1" name="loanID">
              {% for loanID in loanID_list %}
                  <option value="{{ loanID.loanid }}">{{ loanID.loanid }}</option>
              {% endfor %}
          </select>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
    {% if messages %}
        <script>
            {% for msg in messages %}
                alert('{{ msg.message }}');
            {% endfor %}
        </script>
    {% endif %}
</div>

{% endblock %}